# Generated by Django 5.2.4 on 2025-09-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimodels', '0002_aimodel_delete_modelconfiguration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderSchema',
            fields=[
                ('provider_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=255)),
                ('credentials_schema', models.JSONField(default=dict)),
                ('model_blueprints', models.JSONField(default=list)),
            ],
        ),
    ]
