# Generated by Django 5.2.4 on 2025-09-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aimodels', '0003_providerschema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerschema',
            name='credentials_schema',
            field=models.JSONField(default=dict, help_text='The full JSON Schema for credentials, including nested properties.'),
        ),
        migrations.AlterField(
            model_name='providerschema',
            name='model_blueprints',
            field=models.JSONField(default=list, help_text='A JSON array of all model blueprints this provider offers.'),
        ),
    ]
