# Generated by Django 5.2.4 on 2026-02-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0004_alter_node_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='is_used_in_graph',
            field=models.BooleanField(default=False, help_text='True if this node is currently linked to a GNode in the Graph Control Plane (MS14).'),
        ),
    ]
