# Generated by Django 6.0.2 on 2026-02-15 16:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_id', models.UUIDField(db_index=True, help_text='Reference to MS2 Project')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('node_type', models.CharField(choices=[('STANDARD', 'Standard AI Node')], default='STANDARD', max_length=50)),
                ('is_start', models.BooleanField(default=False)),
                ('ms4_node_id', models.UUIDField(blank=True, null=True)),
                ('discribtion', models.TextField(blank=True, default='', null=True)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='graphcontrol.graph')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FFO',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dest_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ffos_as_dest', to='graphcontrol.gnode')),
                ('owner_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ffos', to='graphcontrol.gnode')),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ffos', to='graphcontrol.graph')),
            ],
        ),
        migrations.CreateModel(
            name='FFI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ffis', to='graphcontrol.gnode')),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ffis_as_source', to='graphcontrol.gnode')),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ffis', to='graphcontrol.graph')),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dest_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='graphcontrol.gnode')),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='graphcontrol.gnode')),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='graphcontrol.graph')),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('firing_mode', models.CharField(choices=[('SINGLE', 'Single Input'), ('AND', 'Synchronous (Wait for All)'), ('OR', 'Asynchronous (Fire on Any)')], default='SINGLE', max_length=20)),
                ('is_terminal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='graphcontrol.graph')),
                ('outputs', models.ManyToManyField(blank=True, related_name='fed_by_rules', to='graphcontrol.ffo')),
                ('owner_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='graphcontrol.gnode')),
            ],
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_text', models.TextField()),
                ('placeholder_map', models.JSONField(default=dict)),
                ('rule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_template', to='graphcontrol.rule')),
            ],
        ),
        migrations.CreateModel(
            name='Projection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('op', models.CharField(blank=True, choices=[('SINGLE', 'Single Input'), ('AND', 'Synchronous (Wait for All)'), ('OR', 'Asynchronous (Fire on Any)')], max_length=20, null=True)),
                ('children', models.ManyToManyField(blank=True, related_name='parents', to='graphcontrol.projection')),
                ('ffi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projections', to='graphcontrol.ffi')),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projections', to='graphcontrol.graph')),
                ('owner_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_projections', to='graphcontrol.gnode')),
                ('created_by_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_projections', to='graphcontrol.rule')),
            ],
        ),
        migrations.CreateModel(
            name='RuleInput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('projection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphcontrol.projection')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphcontrol.rule')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='rule',
            name='inputs',
            field=models.ManyToManyField(related_name='used_by_rules', through='graphcontrol.RuleInput', to='graphcontrol.projection'),
        ),
        migrations.AddIndex(
            model_name='gnode',
            index=models.Index(fields=['graph', 'node_type'], name='graphcontro_graph_i_861154_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gnode',
            unique_together={('graph', 'name')},
        ),
        migrations.AddIndex(
            model_name='ffo',
            index=models.Index(fields=['graph', 'owner_node'], name='graphcontro_graph_i_792031_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ffo',
            unique_together={('graph', 'owner_node', 'dest_node')},
        ),
        migrations.AddIndex(
            model_name='ffi',
            index=models.Index(fields=['graph', 'owner_node'], name='graphcontro_graph_i_ab40d7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ffi',
            unique_together={('graph', 'owner_node', 'source_node')},
        ),
        migrations.AddIndex(
            model_name='edge',
            index=models.Index(fields=['graph', 'source_node'], name='graphcontro_graph_i_7ea233_idx'),
        ),
        migrations.AddIndex(
            model_name='edge',
            index=models.Index(fields=['graph', 'dest_node'], name='graphcontro_graph_i_d82f10_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='edge',
            unique_together={('graph', 'source_node', 'dest_node')},
        ),
        migrations.AddIndex(
            model_name='projection',
            index=models.Index(fields=['graph', 'owner_node'], name='graphcontro_graph_i_3771d9_idx'),
        ),
        migrations.AddIndex(
            model_name='projection',
            index=models.Index(fields=['ffi'], name='graphcontro_ffi_id_84eb86_idx'),
        ),
        migrations.AddConstraint(
            model_name='projection',
            constraint=models.UniqueConstraint(condition=models.Q(('ffi__isnull', True)), fields=('owner_node',), name='unique_seed_projection_per_node'),
        ),
        migrations.AddConstraint(
            model_name='ruleinput',
            constraint=models.UniqueConstraint(fields=('projection',), name='unique_projection_usage'),
        ),
        migrations.AddConstraint(
            model_name='ruleinput',
            constraint=models.UniqueConstraint(fields=('rule', 'projection'), name='unique_input_per_rule'),
        ),
        migrations.AddConstraint(
            model_name='ruleinput',
            constraint=models.UniqueConstraint(fields=('rule', 'position'), name='unique_input_position_per_rule'),
        ),
        migrations.AddIndex(
            model_name='rule',
            index=models.Index(fields=['graph', 'owner_node'], name='graphcontro_graph_i_4a90e9_idx'),
        ),
    ]
