# Generated by Django 6.0.2 on 2026-02-15 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphcontrol', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gnode',
            old_name='discribtion',
            new_name='description',
        ),
    ]
