# Generated by Django 6.0 on 2026-02-23 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphcontrol', '0002_rename_discribtion_gnode_description'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='gnode',
            constraint=models.UniqueConstraint(condition=models.Q(('ms4_node_id__isnull', False)), fields=('graph', 'ms4_node_id'), name='unique_ms4_node_per_graph'),
        ),
    ]
