# Generated by Django 6.0 on 2026-03-06 23:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphcontrol', '0003_gnode_unique_ms4_node_per_graph'),
    ]

    operations = [
        migrations.CreateModel(
            name='FBI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='FBO',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='projection',
            name='unique_seed_projection_per_node',
        ),
        migrations.AddField(
            model_name='edge',
            name='edge_type',
            field=models.CharField(choices=[('FORWARD', 'Forward'), ('FEEDBACK', 'Feedback (creates cycle)')], default='FORWARD', help_text='Auto-classified: FORWARD if no cycle, FEEDBACK if closing a cycle.', max_length=20),
        ),
        migrations.AddIndex(
            model_name='edge',
            index=models.Index(fields=['graph', 'edge_type'], name='graphcontro_graph_i_f04efd_idx'),
        ),
        migrations.AddField(
            model_name='fbi',
            name='graph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fbis', to='graphcontrol.graph'),
        ),
        migrations.AddField(
            model_name='fbi',
            name='owner_node',
            field=models.ForeignKey(help_text='The node that receives feedback (the destination / home-run node).', on_delete=django.db.models.deletion.CASCADE, related_name='fbis', to='graphcontrol.gnode'),
        ),
        migrations.AddField(
            model_name='fbi',
            name='source_node',
            field=models.ForeignKey(help_text='The controller node emitting the feedback.', on_delete=django.db.models.deletion.CASCADE, related_name='fbis_as_source', to='graphcontrol.gnode'),
        ),
        migrations.AddField(
            model_name='projection',
            name='fbi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projections', to='graphcontrol.fbi'),
        ),
        migrations.AddIndex(
            model_name='projection',
            index=models.Index(fields=['fbi'], name='graphcontro_fbi_id_ea48d0_idx'),
        ),
        migrations.AddConstraint(
            model_name='projection',
            constraint=models.UniqueConstraint(condition=models.Q(('fbi__isnull', True), ('ffi__isnull', True)), fields=('owner_node',), name='unique_seed_projection_per_node'),
        ),
        migrations.AddField(
            model_name='fbo',
            name='dest_node',
            field=models.ForeignKey(help_text='The node that receives the feedback.', on_delete=django.db.models.deletion.CASCADE, related_name='fbos_as_dest', to='graphcontrol.gnode'),
        ),
        migrations.AddField(
            model_name='fbo',
            name='graph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fbos', to='graphcontrol.graph'),
        ),
        migrations.AddField(
            model_name='fbo',
            name='owner_node',
            field=models.ForeignKey(help_text='The controller node that emits feedback.', on_delete=django.db.models.deletion.CASCADE, related_name='fbos', to='graphcontrol.gnode'),
        ),
        migrations.AddIndex(
            model_name='fbi',
            index=models.Index(fields=['graph', 'owner_node'], name='graphcontro_graph_i_1ee4e1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fbi',
            unique_together={('graph', 'owner_node', 'source_node')},
        ),
        migrations.AddIndex(
            model_name='fbo',
            index=models.Index(fields=['graph', 'owner_node'], name='graphcontro_graph_i_7d82b4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fbo',
            unique_together={('graph', 'owner_node', 'dest_node')},
        ),
    ]
