# Generated by Django 6.0 on 2026-03-07 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphcontrol', '0004_feedback_foundation'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='fbo_outputs',
            field=models.ManyToManyField(blank=True, help_text='FBO channels this controller rule writes back to (creates ~X[] feedback context).', related_name='fed_by_rules', to='graphcontrol.fbo'),
        ),
    ]
