# Generated by Django 6.0.2 on 2026-03-10 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphcontrol', '0005_rule_fbo_outputs'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='is_infinite',
            field=models.BooleanField(default=False, help_text='If True, loop has no bounds (use with caution).'),
        ),
        migrations.AddField(
            model_name='rule',
            name='max_iterations',
            field=models.PositiveIntegerField(default=3, help_text='Max times this feedback loop can execute.'),
        ),
    ]
