# Generated by Django 6.0 on 2026-03-10 19:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphcontrol', '0006_rule_is_infinite_rule_max_iterations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='is_infinite',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='max_iterations',
        ),
        migrations.CreateModel(
            name='RuleFBOOutput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('max_iterations', models.PositiveIntegerField(blank=True, default=3, help_text='Max times this specific feedback loop can execute. Null if infinite.', null=True)),
                ('is_infinite', models.BooleanField(default=False, help_text='If True, loop has no bounds (bypasses max_iterations).')),
                ('fbo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphcontrol.fbo')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphcontrol.rule')),
            ],
        ),
        migrations.RemoveField(
            model_name='rule',
            name='fbo_outputs',
        ),
        migrations.AddField(
            model_name='rule',
            name='fbo_outputs',
            field=models.ManyToManyField(blank=True, help_text='FBO channels this controller rule writes back to (creates ~X[] feedback context).', related_name='fed_by_rules', through='graphcontrol.RuleFBOOutput', to='graphcontrol.FBO'),
        ),
        migrations.AddConstraint(
            model_name='rulefbooutput',
            constraint=models.UniqueConstraint(fields=('rule', 'fbo'), name='unique_fbo_per_rule'),
        ),
    ]
