# Generated by Django 6.0.2 on 2026-03-11 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphcontrol', '0007_remove_rule_is_infinite_remove_rule_max_iterations_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='projection',
            name='unique_seed_projection_per_node',
        ),
        migrations.RemoveConstraint(
            model_name='ruleinput',
            name='unique_projection_usage',
        ),
        migrations.RemoveIndex(
            model_name='projection',
            name='graphcontro_ffi_id_84eb86_idx',
        ),
        migrations.RemoveIndex(
            model_name='projection',
            name='graphcontro_fbi_id_ea48d0_idx',
        ),
        migrations.RemoveField(
            model_name='rulefbooutput',
            name='is_infinite',
        ),
        migrations.RemoveField(
            model_name='rulefbooutput',
            name='max_iterations',
        ),
        migrations.AddField(
            model_name='projection',
            name='collapse_target_projection',
            field=models.ForeignKey(blank=True, help_text='Baseline projection this home-run collapses into.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_run_views_collapsing_here', to='graphcontrol.projection'),
        ),
        migrations.AddField(
            model_name='projection',
            name='context_family',
            field=models.CharField(choices=[('FORWARD', 'Forward'), ('FEEDBACK', 'Feedback')], default='FORWARD', max_length=20),
        ),
        migrations.AddField(
            model_name='projection',
            name='home_run_controller_rule',
            field=models.ForeignKey(blank=True, help_text='Controller rule that owns this home-run display projection.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_run_views', to='graphcontrol.rule'),
        ),
        migrations.AddField(
            model_name='projection',
            name='is_reusable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projection',
            name='is_selectable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projection',
            name='projection_kind',
            field=models.CharField(choices=[('NORMAL', 'Normal selectable projection'), ('HOME_RUN_VIEW', 'Non-selectable home-run view')], default='NORMAL', max_length=30),
        ),
        migrations.AddField(
            model_name='rule',
            name='baseline_projection',
            field=models.ForeignKey(blank=True, help_text='The original forward input slice that this controller collapses back into.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controller_baseline_for_rules', to='graphcontrol.projection'),
        ),
        migrations.AddField(
            model_name='rule',
            name='completion_policy',
            field=models.CharField(choices=[('FIRST_RETURN_WINS', 'First return wins'), ('BARRIER_REQUIRED_RETURNS', 'Barrier required returns')], default='FIRST_RETURN_WINS', max_length=50),
        ),
        migrations.AddField(
            model_name='rule',
            name='is_infinite_loop',
            field=models.BooleanField(default=False, help_text='If true, this controller loop has no max iteration cap.'),
        ),
        migrations.AddField(
            model_name='rule',
            name='max_iterations',
            field=models.PositiveIntegerField(blank=True, help_text='Max completed iterations for controller rules. Ignored if is_infinite_loop=True.', null=True),
        ),
        migrations.AlterField(
            model_name='projection',
            name='created_by_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_projections', to='graphcontrol.rule'),
        ),
        migrations.AlterField(
            model_name='projection',
            name='owner_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projections', to='graphcontrol.gnode'),
        ),
        migrations.AddIndex(
            model_name='projection',
            index=models.Index(fields=['graph', 'owner_node', 'projection_kind'], name='graphcontro_graph_i_0dabff_idx'),
        ),
        migrations.AddIndex(
            model_name='projection',
            index=models.Index(fields=['graph', 'home_run_controller_rule'], name='graphcontro_graph_i_c46e32_idx'),
        ),
    ]
