# Generated by Django 6.0 on 2026-03-11 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphcontrol', '0009_add_max_iterations_to_rule'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='projection',
            name='graphcontro_graph_i_0dabff_idx',
        ),
        migrations.RemoveIndex(
            model_name='projection',
            name='graphcontro_graph_i_c46e32_idx',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='baseline_projection',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='completion_policy',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='is_infinite_loop',
        ),
        migrations.AlterField(
            model_name='projection',
            name='created_by_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_projections', to='graphcontrol.rule'),
        ),
        migrations.AlterField(
            model_name='projection',
            name='owner_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_projections', to='graphcontrol.gnode'),
        ),
        migrations.AlterField(
            model_name='rulefbooutput',
            name='fbo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_links', to='graphcontrol.fbo'),
        ),
        migrations.AlterField(
            model_name='rulefbooutput',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fbo_output_links', to='graphcontrol.rule'),
        ),
        migrations.AddIndex(
            model_name='projection',
            index=models.Index(fields=['ffi'], name='graphcontro_ffi_id_84eb86_idx'),
        ),
        migrations.AddIndex(
            model_name='projection',
            index=models.Index(fields=['fbi'], name='graphcontro_fbi_id_ea48d0_idx'),
        ),
        migrations.AddConstraint(
            model_name='projection',
            constraint=models.UniqueConstraint(condition=models.Q(('fbi__isnull', True), ('ffi__isnull', True)), fields=('owner_node',), name='unique_seed_projection_per_node'),
        ),
        migrations.AddConstraint(
            model_name='ruleinput',
            constraint=models.UniqueConstraint(fields=('projection',), name='unique_projection_usage'),
        ),
        migrations.RemoveField(
            model_name='projection',
            name='collapse_target_projection',
        ),
        migrations.RemoveField(
            model_name='projection',
            name='context_family',
        ),
        migrations.RemoveField(
            model_name='projection',
            name='home_run_controller_rule',
        ),
        migrations.RemoveField(
            model_name='projection',
            name='is_reusable',
        ),
        migrations.RemoveField(
            model_name='projection',
            name='is_selectable',
        ),
        migrations.RemoveField(
            model_name='projection',
            name='projection_kind',
        ),
    ]
