# Generated by Django 6.0 on 2026-03-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphcontrol', '0010_sync_rulefbooutput_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='is_router',
            field=models.BooleanField(default=False, help_text='If True, instructs the model to dynamically choose which outputs receive data.'),
        ),
    ]
