# Generated by Django 5.2.6 on 2025-09-22 19:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner_id', models.UUIDField(db_index=True)),
                ('project_id', models.UUIDField(db_index=True)),
                ('strategy_type', models.CharField(default='vector_db', max_length=100)),
                ('config', models.JSONField(default=dict)),
                ('vector_store_collection_name', models.CharField(blank=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileCollectionLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_id', models.UUIDField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ingesting', 'Ingesting'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=20)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_files', to='rag_control_plane.knowledgecollection')),
            ],
            options={
                'unique_together': {('collection', 'file_id')},
            },
        ),
    ]
