# Generated by Django 5.2.7 on 2025-10-02 17:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocalModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('huggingface_id', models.CharField(help_text="e.g., 'meta-llama/Llama-2-7b-chat-hf'", max_length=255, unique=True)),
                ('status', models.CharField(choices=[('not_installed', 'Not Installed'), ('downloading', 'Downloading'), ('downloaded', 'Downloaded'), ('error', 'Error'), ('active', 'Active')], default='not_installed', max_length=20)),
                ('local_path', models.CharField(blank=True, help_text='Absolute path to the model files on the host machine.', max_length=1024, null=True)),
                ('capabilities', models.JSONField(default=list, help_text="Capabilities inferred from the model config, e.g., ['text', 'tool_use']")),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('starting', 'Starting'), ('healthy', 'Healthy'), ('unhealthy', 'Unhealthy'), ('stopping', 'Stopping')], default='starting', max_length=20)),
                ('container_id', models.CharField(max_length=255, unique=True)),
                ('internal_endpoint', models.CharField(help_text="Internal Docker IP and port, e.g., 'http://172.17.0.5:80'", max_length=255)),
                ('gpu_uuid', models.CharField(blank=True, help_text='UUID of the assigned GPU, if any.', max_length=255, null=True)),
                ('last_health_check', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('local_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='lrs.localmodel')),
            ],
        ),
    ]
