# Generated by Django 5.2.7 on 2025-10-02 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lrs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelinstance',
            name='health_check_url',
            field=models.CharField(blank=True, help_text='Publicly mapped URL for the health checker, e.g., http://localhost:12345', max_length=255, null=True),
        ),
    ]
