# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rag.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'rag.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trag.proto\x12\x03rag\"W\n\x0fRetrieveRequest\x12\x15\n\rcollection_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\r\n\x05query\x18\x03 \x01(\t\x12\r\n\x05top_k\x18\x04 \x01(\x05\"\x94\x01\n\rDocumentChunk\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x32\n\x08metadata\x18\x02 \x03(\x0b\x32 .rag.DocumentChunk.MetadataEntry\x12\r\n\x05score\x18\x03 \x01(\x02\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"6\n\x10RetrieveResponse\x12\"\n\x06\x63hunks\x18\x01 \x03(\x0b\x32\x12.rag.DocumentChunk\">\n\x1bUpdateFileLinkStatusRequest\x12\x0f\n\x07link_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"/\n\x1cUpdateFileLinkStatusResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32S\n\nRAGService\x12\x45\n\x16RetrieveRelevantChunks\x12\x14.rag.RetrieveRequest\x1a\x15.rag.RetrieveResponse2q\n\x12RAGInternalService\x12[\n\x14UpdateFileLinkStatus\x12 .rag.UpdateFileLinkStatusRequest\x1a!.rag.UpdateFileLinkStatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rag_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DOCUMENTCHUNK_METADATAENTRY']._loaded_options = None
  _globals['_DOCUMENTCHUNK_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_RETRIEVEREQUEST']._serialized_start=18
  _globals['_RETRIEVEREQUEST']._serialized_end=105
  _globals['_DOCUMENTCHUNK']._serialized_start=108
  _globals['_DOCUMENTCHUNK']._serialized_end=256
  _globals['_DOCUMENTCHUNK_METADATAENTRY']._serialized_start=209
  _globals['_DOCUMENTCHUNK_METADATAENTRY']._serialized_end=256
  _globals['_RETRIEVERESPONSE']._serialized_start=258
  _globals['_RETRIEVERESPONSE']._serialized_end=312
  _globals['_UPDATEFILELINKSTATUSREQUEST']._serialized_start=314
  _globals['_UPDATEFILELINKSTATUSREQUEST']._serialized_end=376
  _globals['_UPDATEFILELINKSTATUSRESPONSE']._serialized_start=378
  _globals['_UPDATEFILELINKSTATUSRESPONSE']._serialized_end=425
  _globals['_RAGSERVICE']._serialized_start=427
  _globals['_RAGSERVICE']._serialized_end=510
  _globals['_RAGINTERNALSERVICE']._serialized_start=512
  _globals['_RAGINTERNALSERVICE']._serialized_end=625
# @@protoc_insertion_point(module_scope)
